### ISSUE TITLE
Details by OSM type

### ISSUE THREAD

**Issue by sabas** [Xevib/osmbot#12]
/search Genoa

returns a list of cities: Genoa, Italy is http://www.openstreetmap.org/relation/44875 but it's a relation.
/details 66586322 gives info for the node, but 
/details 44875 gives no result

Suggestions:
- Change the /details parameter to accept queries in the form /detail {type}/{id}
- Add specific commands: /node, /way, /relation

**Comment by Xevib** [comment]
Thank you for the advice, that commit should fix the bug
