### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by pokoli** [Xevib/osmbot#2]
Following https://github.com/blog/1530-choosing-an-open-source-license it will be great to have a license for the project

**Comment by pokoli** [comment]
Be aware: "the absence of a license means that the default copyright laws apply" https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by Xevib** [comment]
Thanks for the advice i set GPL 3

**Comment by pokoli** [comment]
Good choice!
