### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by dbf256** [Xevib/osmbot#241]
https://travis-ci.org/Xevib/osmbot/builds/185373963

**Comment by Xevib** [comment]
I tried to install osmapi on a clean virtualv and it fails so I supose that is a bug of osmapi

**Comment by Xevib** [comment]
I opened a bug on osmapi https://github.com/metaodi/osmapi/issues/67

**Comment by Xevib** [comment]
I did a fix on the travis and now its working
