### ISSUE TITLE
osmbot not working from India

### ISSUE THREAD

**Issue by kirantpatil** [Xevib/osmbot#245]
Hi,

I tried to access osmbot and none of the commands are working as shown in below image.

![screenshot_20170909-173540](https://user-images.githubusercontent.com/1178055/30240025-ae05db18-9557-11e7-876d-54d09182c42e.png)

Thanks.

**Comment by Xevib** [comment]
@kirantpatil Hi,
I seen that the uwsgi process died.
I have been doing some improvements on the process manager that launches the bot on the server and this should not repeat.

Thank you
