### ISSUE TITLE
Configure the bot to directly answer the user

### ISSUE THREAD

**Issue by naoliv** [Xevib/osmbot#45]
We have a Telegram channel here in Brazil and people usually message the bot for help (`/help@OSMbot`). Since the bot is in the channel, all the answers are replied there too.

One drawback is that the messages end up polluting the channel (imagine a lot of curious users trying to see what the bot can do or answer).

Is it possible to configure the bot to answer the user directly, instead sending the help messages, for example, to the channel?

If not, is it possible to implement this?

**Comment by Xevib** [comment]
It seems logic, by default the bots allways answer all the commands(event if there are more than one bot on the channel).
I will explore the posibility to have channel settings and be able to configure it only to answer when it's mentioned with the @

Thank you for the issue

**Comment by Xevib** [comment]
We fixed this issue on https://github.com/Xevib/osmbot/pull/46 but some clients like Telegram Desktop now allow to send a command to a specific bot
