### ISSUE TITLE
Getting OSM bot more easily found and explored on Bing search

### ISSUE THREAD

**Issue by gurprep** [Xevib/osmbot#49]
@Bing we are trying to make it easier for users to discover, find and explore Bots on Bing. I would like to chat more about this but need a way to contact you. Please send me your contact information/phone number and a time we can connect and discuss the opportunity in more detail.
Regards
G S Pall
Bing for Partners

**Comment by gurprep** [comment]
my email is gurprep@microsoft.com

**Comment by Xevib** [comment]
Please contact through the email in my profile
