### ISSUE TITLE
Styling: Links in details message and title

### ISSUE THREAD

**Issue by KonfrareAlbert** [Xevib/osmbot#59]
Now:
![belgica](https://cloud.githubusercontent.com/assets/6559793/15993718/d065ede8-30ee-11e6-8ae7-c46ae845e573.png)

Could be better:
* «Tags for» title in **bold** («Etiquetes per a» in screenshot)
* Styled link for flag URL (I suggest: [Wikimedia Commons: Flag](https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg) or [Commons: Flag](https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg). The word «Flag» could be translated)
* Styled link for Wikidata URL (I suggest: [Wikidata: Q31](https://www.wikidata.org/wiki/Q31). Wikidata could be translated)
* Styled link for Wikipedia URL (I suggest: [Wikipedia: Belgique](https://fr.wikipedia.org/wiki/Belgique). Wikipedia could be translated)

**Comment by Ecron** [comment]
I totally like this idea. I'd go even further and put the signature in italics, so it results like *Col·laboradors de l'OpenStreetMap*. Also, I don't understand why that message has not a picture preview of the first link (the svg picture). That'd be a great improvement also, to get a flag preview.

**Comment by KonfrareAlbert** [comment]
Closed #96

**Comment by KonfrareAlbert** [comment]
Closed #96
