### ISSUE TITLE
Bug: Not translated text in /about command

### ISSUE THREAD

**Issue by KonfrareAlbert** [Xevib/osmbot#61]
These strings are untranslated in bot (but translated on Transifex):
* **Code**
* **Localization**
* **Telegram channel**
* **Please rate me**

Tested in different languages

Link:
[OSMbot translations on Transifex](https://www.transifex.com/osm-catala/osmbot/)

**Comment by Xevib** [comment]
The error is now fixed but will appear wrong in some languages until it will be updated
