### ISSUE TITLE
Use of name:xx in inline bot

### ISSUE THREAD

**Issue by KonfrareAlbert** [Xevib/osmbot#66]
Same issue that the #58 , but for inline bot. 
Perhaps the same solution in the same settings ;)

Problems now:
![tokio](https://cloud.githubusercontent.com/assets/6559793/16019069/772f8626-31a7-11e6-9c16-c1ac020c84a5.png)
Another example:
![stpeter](https://cloud.githubusercontent.com/assets/6559793/16019082/8180787e-31a7-11e6-9b38-9f8a0f63465c.png)

Another solution (I don't like this) could be to type a language code in the inline search:
* @OSMbot en tokio
  * Returns results in English (name:en)
* @OSMbot ca sant petersburg
  * Returns results in Catalan (name:ca)

**Comment by Ecron** [comment]
The second option is a good idea also, you can set a label for the inline bot like "@OSMbot *country_code* *query*", so users know that they can specify the result's language.

**Comment by Xevib** [comment]
Fixed
