### ISSUE TITLE
Styling results in inline query

### ISSUE THREAD

**Issue by KonfrareAlbert** [Xevib/osmbot#69]
Now, you can see these results for inline query in @OSMbot:

![osmbot](https://cloud.githubusercontent.com/assets/6559793/16051316/8f1c8f28-325f-11e6-826b-c438df82a9e7.png)

It's necessary to style the results like the Wikipedia bot:
* **name** (big typo, black and bold)
* another info (smaller typo and grey)
Two strings with newlines if content is broken.
An example:

![wiki](https://cloud.githubusercontent.com/assets/6559793/16051380/d4cb0efa-325f-11e6-869e-b32591516914.png)

**Comment by Ecron** [comment]
Ugh, that's indeed an awful display, comparing both bots. OSMbot truly needs inline formatting :+1::+1:
