### ISSUE TITLE
Got a very small map

### ISSUE THREAD

**Issue by Zverik** [Xevib/osmbot#87]
`/map 12`, then sent a current location.

Got:
![425211676_2317822112527789700](https://cloud.githubusercontent.com/assets/766031/16447892/c5b634e8-3dff-11e6-816b-1807efaf6914.jpg)

**Comment by Xevib** [comment]
Thank you for the feedback, can you try to use /map+ location? 
I will try to make the map bounding box zoom dependent as the /map alone command does

**Comment by Zverik** [comment]
For a simple `/map` + location I've got a map of a reasonable size.
